package edu.iastate.cs472.proj1;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 *  
 * @author Josh Seeley
 *	
 * Modified and added to functions solve8Puzzle, Astar, solutionPath
 * 
 */

public class EightPuzzle 
{
	/**
	 * This static method solves an 8-puzzle with a given initial state using three heuristics. The 
	 * first two, allowing single moves only, compare the board configuration with the goal configuration 
	 * by the number of mismatched tiles, and by the Manhattan distance, respectively.  The third 
	 * heuristic, designed by yourself, allows double moves and must be also admissible.  The goal 
	 * configuration set for all puzzles is
	 * 
	 * 			1 2 3
	 * 			8   4
	 * 			7 6 5
	 * 
	 * @param s0
	 * @return a string specified in the javadoc below
	 */
	public static String solve8Puzzle(State s0)
	{
		// TODO 
		
		// 1) If there exists no solution, return a message that starts with "No solution 
		//    exists for the following initial state:" and follows with a blank line and 
		//    then what would be the output from a call s0.toString(). See the end of 
		//    Section 6 in the project description for an example. 
		if(!s0.solvable()){
			return "No solution exists for the following initial state:\n" + s0.toString();
		}		

		// 2) Otherwise, solve the puzzle with the three heuristics.  The two solutions generated by
		//    the first two heuristics may be different but must have the same length for optimality. 
		
		Heuristic h[] = {Heuristic.TileMismatch, Heuristic.ManhattanDist, Heuristic.DoubleMoveHeuristic }; 
		String [] moves = new String[3]; 
		
		for (int i = 0; i < 3; i++)
		{
			moves[i] = AStar(s0, h[i]); 
		}
		
		// 3) Combine the three solution strings into one that would print out in the 
		//    output format specified in Section 6 of the project description.
		
		return moves[0] + "\n" + moves[1] + "\n" + moves[2]; 
	}

	
	/**
	 * This method implements the A* algorithm to solve the 8-puzzle with an input initial state s0. 
	 * The algorithm implementation is described in Section 3 of the project description. 
	 * 
	 * Precondition: the puzzle is solvable with the initial state s0.
	 * 
	 * @param s0  initial state
	 * @param h   heuristic 
	 * @return    solution string 
	 */
	public static String AStar(State s0, Heuristic h)
	{
		
		// TODO 

		// Initialize the two lists used by the algorithm. 
		OrderedStateList OPEN = new OrderedStateList(h, true); 
		OrderedStateList CLOSE = new OrderedStateList(h, false);
					
		
		// Implement the algorithm described in Section 3 to solve the puzzle. 
		// Once a goal state s is reached, call solutionPath(s) and return the solution string. 
		s0.numMoves = 0;
		State.heu = h;
		OPEN.addState(s0);
		
		while(OPEN.size() != 0) {
			State s = OPEN.remove();
			CLOSE.addState(s);

			if(s.isGoalState()){
				return solutionPath(s);
			}
			
			List<Move> pmoves = new ArrayList<>(Arrays.asList(Move.LEFT, Move.RIGHT, Move.UP, Move.DOWN));

			 if (h == Heuristic.DoubleMoveHeuristic) {
                pmoves.addAll(Arrays.asList(Move.DBL_LEFT, Move.DBL_RIGHT, Move.DBL_UP, Move.DBL_DOWN));
            }

            for (Move m : pmoves) {
                State t;
                try {
                    t = s.successorState(m);
                } catch (IllegalArgumentException e) {
                    continue;
                }

                if (t == null) continue;

                t.predecessor = s;
				t.move = m;
				t.numMoves = s.numMoves +1;
				int fNew = t.cost();

                State openMatch = OPEN.findState(t);
                State closedMatch = CLOSE.findState(t);

                if (openMatch == null && closedMatch == null) {
                    OPEN.addState(t);
                }
                
                else if (openMatch != null && fNew < openMatch.cost()) {
                    openMatch.predecessor = s;
                    openMatch.numMoves = t.numMoves;
                }
                
                else if (closedMatch != null && fNew < closedMatch.cost()) {
                    closedMatch.predecessor = s;
                    closedMatch.numMoves = t.numMoves;
                    CLOSE.removeState(closedMatch);
                    OPEN.addState(closedMatch);
                }
            }
        }

        return "No solution found";
    }	
	
	
	
	/**
	 * From a goal state, follow the predecessor link to trace all the way back to the initial state. 
	 * Meanwhile, generate a string to represent board configurations in the reverse order, with 
	 * the initial configuration appearing first. Between every two consecutive configurations 
	 * is the move that causes their transition. A blank line separates a move and a configuration.  
	 * In the string, the sequence is preceded by the total number of moves and a blank line. 
	 * 
	 * See Section 6 in the projection description for an example. 
	 * 
	 * Call the toString() method of the State class. 
	 * 
	 * @param goal
	 * @return
	 */
	private static String solutionPath(State goal)
	{
		// TODO 
		String heuristicName = "";
		ArrayList<State> pp = new ArrayList<>();
		State c = goal;
		while(c != null){
			pp.add(c);
			c = c.predecessor;
		}
		Collections.reverse(pp);

		if(State.heu == Heuristic.TileMismatch){
			heuristicName = "number of mismatched tiles";
		}else if(State.heu == Heuristic.ManhattanDist) {
			heuristicName = "the Manhattan distance";
		} else if(State.heu == Heuristic.DoubleMoveHeuristic){
			heuristicName = "double moves allowed";
		}

		StringBuilder sb = new StringBuilder();
		sb.append(pp.size() - 1).append(" moves in total (heuristic: ").append(heuristicName).append(")\n\n");

		for (int i = 0; i < pp.size(); i++) {
			sb.append(pp.get(i).toString()).append("\n");
			if (i < pp.size() - 1) {
				sb.append(pp.get(i + 1).move).append("\n\n");
			}
		}

		return sb.toString();
	}
	
}
