package edu.iastate.cs472.proj1;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 *  
 * @author Josh Seeley
 * 
 * I added or modified the functions State(file), State(board), successorState, solvable, isGoalState, toString, clone, equals, cost, compareTo,
 * computeNumMismatchedTiles, computeManhattanDistance, computeNumSingleDoubleMoves
 * 
 *
 */


/**
 * This class represents a board configuration in the 8-puzzle.  Only the initial configuration is 
 * generated by a constructor, while intermediate configurations will be generated via calling
 * the method successorState().  State objects will form two circular doubly-linked lists OPEN and 
 * CLOSED, which will be used by the A* algorithm to search for a path from a given initial board
 * configuration to the final board configuration below: 
 * 
 *  1 2 3 
 *  8   4
 *  7 6 5
 *
 * The final configuration (i.e., the goal state) above is not explicitly represented as an object 
 * of the State class. 
 */

public class State implements Cloneable, Comparable<State>
{
	public int[][] board; 		// configuration of tiles 
	
	public State previous;    	// previous node on the OPEN/CLOSED list
	public State next; 			// next node on the OPEN/CLOSED list
	public State predecessor; 	// predecessor node on the path from the initial state 
	
	public Move move;           // the move that generated this state from its predecessor
	public int numMoves; 	    // number of moves from the initial state to this state

	public static Heuristic heu; // heuristic used. shared by all the states. 
	
	private int numMismatchedTiles = -1;    // number of mismatched tiles between this state 
	                                        // and the goal state; negative if not computed yet.
	private int ManhattanDistance = -1;     // Manhattan distance between this state and the 
	                                        // goal state; negative if not computed yet. 
	private int numSingleDoubleMoves = -1;  // number of single and double moves with each double 
										    // move counted as one; negative if not computed yet. 


	
	/**
	 * Constructor (for the initial state).  
	 * 
	 * It takes a 2-dimensional array representing an initial board configuration. The empty 
	 * square is represented by the number 0.  
	 * 
	 *     a) Initialize all three links previous, next, and predecessor to null.  
	 *     b) Set move to null and numMoves to zero.
	 * 
	 * @param board
	 * @throws IllegalArgumentException		if board is not a 3X3 array or its nine entries are 
	 * 										not respectively the digits 0, 1, ..., 8. 
	 */
    public State(int[][] board) throws IllegalArgumentException 
    {
    	// TODO 
        if(board.length != 3 || board[0].length != 3){
            throw new IllegalArgumentException("Not a 3x3 board");
        }
        for(int i = 0; i < 3; i++){
            for(int j = 0; j < 3; j++){
                if(board[i][j] < 0 || board[i][j] > 8){
                    throw new IllegalArgumentException("Only use characters 0 through 8");
                }
            }
        }
        this.board = new int[3][3];
        for(int i = 0; i < 3; i++){
            for(int j = 0; j < 3; j++){
                this.board[i][j] = board[i][j];
            }
        }
        this.previous = null;
        this.next = null;
        this.predecessor = null;
        this.move = null;
        this.numMoves = 0;
	}
    
    
    /**
     * Constructor (for the initial state) 
     * 
     * It takes a state from an input file that has three rows, each containing three digits 
     * separated by exactly one blank.  Every row starts with a digit. The nine digits are 
     * from 0 to 8 with no duplicates.  
     * 
     * Do the same initializations as for the first constructor. 
     * 
     * @param inputFileName
     * @throws FileNotFoundException
     * @throws IllegalArgumentException  if the file content does not meet the above requirements. 
     */
    public State (String inputFileName) throws FileNotFoundException, IllegalArgumentException
    {
    	// TODO 
        Scanner s = new Scanner(new File(inputFileName));
        board = new int[3][3];

        for(int i = 0; i < 3; i++){
            for(int j = 0; j < 3; j++){
                if(!s.hasNextInt()){
                    s.close();
                    throw new IllegalArgumentException("File does not meet requirements");
                }
                int v = s.nextInt();
                if(v < 0 || v > 8){
                    s.close();
                    throw new IllegalArgumentException("Only use characters 0 through 8");
                }
                 board[i][j] = v; 

            }
        }
        s.close();
         this.previous = null;
        this.next = null;
        this.predecessor = null;
        this.move = null;
        this.numMoves = 0;
        
	}
    
    
    /**
     * Generate the successor state resulting from a given move.  Throw an exception if the move 
     * cannot be executed.  Besides setting the array board[][] properly, you also need to do the 
     * following:
     * 
     *     a) set the predecessor of the successor state to this state;
     *     b) set the private instance variable move of the successor state to the parameter m; 
     *     c) Set the links next and previous to null;  
     *     d) Set the variable numMoves for the successor state to this.numMoves + 1. 
     * 
     * @param m  one of the moves LEFT, RIGHT, UP, DOWN, DBL_LEFT, DBL_RIGHT, DBL_UP, and DBL_DOWN
     * @return null  			if the successor state is this.predecessor
     *         successor state  otherwise 
     * @throws IllegalArgumentException if LEFT when the empty square is in the right column, or  
     *                                  if RIGHT when the empty square is in the left column, or
     *                                  if UP when the empty square is in the bottom row, or 
     *                                  if DOWN when the empty square is in the top row, or
     *                                  if DBL_LEFT when the empty square is not in the left column, or 
     *                                  if DBL_RIGHT when the empty square is not in the right column, or 
     *                                  if DBL_UP when the empty square is not in the top row, or 
     *                                  if DBL_DOWN when the empty square is not in the bottom row. 
     */                                  
    public State successorState(Move m) throws IllegalArgumentException 
    {
    	// TODO 
        int row = -1, col = -1;
        for(int i = 0; i < 3; i++){
            for(int j = 0; j < 3; j++){
                if(board[i][j] == 0){
                    col = j;
                    row = i;
                }
            }
        }
        int newRow = row, newCol = col;
        State newState = (State) this.clone();
    	newState.predecessor = this;
    	newState.previous = null;
    	newState.next = null;
    	newState.move = m;
    	newState.numMoves = this.numMoves + 1;

        switch (m) {
    case LEFT:
        if (col == 2) throw new IllegalArgumentException();
        newCol = col + 1;
        break;

    case RIGHT:
        if (col == 0) throw new IllegalArgumentException();
        newCol = col - 1;
        break;

    case UP:
        if (row == 2) throw new IllegalArgumentException();
        newRow = row + 1;
        break;

    case DOWN:
        if (row == 0) throw new IllegalArgumentException();
        newRow = row - 1;
        break;

    case DBL_LEFT:
        if (col != 0) throw new IllegalArgumentException();
        int tempL1 = newState.board[row][0];
        newState.board[row][0] = newState.board[row][1];
        newState.board[row][1] = tempL1;

        int tempL2 = newState.board[row][1];
        newState.board[row][1] = newState.board[row][2];
        newState.board[row][2] = tempL2;

        return newState;

    case DBL_RIGHT:
        if (col != 2) throw new IllegalArgumentException();
        int tempR1 = newState.board[row][2];
        newState.board[row][2] = newState.board[row][1];
        newState.board[row][1] = tempR1;

        int tempR2 = newState.board[row][1];
        newState.board[row][1] = newState.board[row][0];
        newState.board[row][0] = tempR2;

        return newState;

    case DBL_UP:
        if (row != 0) throw new IllegalArgumentException();
        int tempU1 = newState.board[0][col];
        newState.board[0][col] = newState.board[1][col];
        newState.board[1][col] = tempU1;

        int tempU2 = newState.board[1][col];
        newState.board[1][col] = newState.board[2][col];
        newState.board[2][col] = tempU2;

        return newState;

    case DBL_DOWN:
        if (row != 2) throw new IllegalArgumentException();
        int tempD1 = newState.board[2][col];
        newState.board[2][col] = newState.board[1][col];
        newState.board[1][col] = tempD1;

        int tempD2 = newState.board[1][col];
        newState.board[1][col] = newState.board[0][col];
        newState.board[0][col] = tempD2;

        return newState;

    default:
        throw new IllegalArgumentException();
}

    int temp = newState.board[row][col];
    newState.board[row][col] = newState.board[newRow][newCol];
    newState.board[newRow][newCol] = temp;

if (this.predecessor != null && newState.equals(this.predecessor))
    return null;

return newState;
    }
    /**
     * Determines if the board configuration in this state can be rearranged into the goal configuration. 
     * According to the PowerPoint notes that introduce the 8-puzzle, we check if this state has an odd number 
     * of inversions. 
     */
    /**
     * 
     * @return true if the puzzle starting in this state can be rearranged into the goal state.
     */
    public boolean solvable()
    {
    	// TODO 
        int inversions = 0;
        for(int i = 0; i < 3; i++){
            for(int j = 0; j < 3; j++){
                int current = board[i][j];
                if(current == 0){
                    continue;
                }
                for(int newi = i; newi < 3; newi++){
                    for(int newj = (newi == i ? j + 1 : 0); newj < 3; newj++){
                        int n = board[newi][newj];
                        if(n != 0 && current > n){
                            inversions++;
                        }
                    }
                }
            }
        }
    	return inversions % 2 != 0; 
    }
    
    
    /**
     * Check if this state is the goal state, namely, if the array board[][] stores the following contents: 
     * 
     * 		1 2 3 
     * 		8 0 4 
     * 		7 6 5 
     * 
     * @return
     */
    public boolean isGoalState()
    {
    	// TODO 
        int[][] goal = {{1,2,3},{8,0,4},{7,6,5}};
        for(int i = 0; i < 3; i++){
            for(int j = 0; j < 3; j++){
                if(board[i][j] != goal[i][j]){
                    return false;
                }
            }
        }
    	return true; 
    }
    
    
    /**
     * Write the board configuration according to the following format:
     * 
     *     a) Output row by row in three lines with no indentations.  
     *     b) Two adjacent tiles in each row have exactly one blank in between. 
     *     c) The empty square is represented by a blank.  
     *     
     * For example, 
     * 
     * 2   3
     * 1 8 4
     * 7 6 5  
     * 
     */
    @Override 
    public String toString()
    {
    	// TODO 
       StringBuilder boardstring = new StringBuilder();
        for(int i = 0; i < 3; i++){
            for(int j = 0; j < 3; j++){
                if (board[i][j] == 0){
                    boardstring.append(" "); 
                }
    			else{
                    boardstring.append(board[i][j]);
                } 
    			if (j < 2){
                   boardstring.append(" ");  
                } 
            }
            boardstring.append("\n");
        }
    	return boardstring.toString(); 
    }
    
    
    /**
     * Create a clone of this State object by copying over the board[][]. Set the links previous,
     * next, and predecessor to null. 
     * 
     * The method is called by SuccessorState(); 
     */
    @Override
    public Object clone()
    {
    	// TODO 
        int[][] board2 = new int[3][3];
        for(int i = 0; i < 3; i++){
            for(int j = 0; j < 3; j++){
                board2[i][j] = this.board[i][j]; 
            }
        }
        State clone = new State(board2);
        clone.previous = null;
        clone.next = null;
        clone.predecessor = null;
    	return clone; 
    }
  

    /**
     * Compare this state with the argument state.  Two states are equal if their arrays board[][] 
     * have the same content.
     */
    @Override 
    public boolean equals(Object o)
    {
    	// TODO 
        State newstate = (State) o;
        for(int i = 0; i < 3; i++){
            for(int j = 0; j < 3; j++){
                if(newstate.board[i][j] != this.board[i][j]){
                    return false;
                }
            }
        }
    	return true; 
    }
        
    
    /**
     * Evaluate the cost of this state as the sum of the number of moves from the initial state and 
     * the estimated number of moves to the goal state using the heuristic stored in the instance 
     * variable heu. 
     * 
     * If heu == TileMismatch, add up numMoves and the return values from computeNumMismatchedTiles().
     * If heu == MahattanDist, add up numMoves and the return values of computeMahattanDistance(). 
     * If heu == DoubleMoveHeuristic, add up numMoves and the return value of computeNumSingleDoubleMoves(). 
     * 
     * @return estimated number of moves from the initial state to the goal state via this state.
     * @throws IllegalArgumentException if heuristic is none of TileMismatch, MahattanDist, DoubleMoveHeuristic. 
     */
    public int cost() throws IllegalArgumentException
    {
    	// TODO 
        if(heu == Heuristic.TileMismatch){
            return numMoves + computeNumMismatchedTiles();
        } else if(heu == Heuristic.ManhattanDist){
            return numMoves + computeManhattanDistance();
        } else if(heu == Heuristic.DoubleMoveHeuristic){
            return numMoves + computeNumSingleDoubleMoves();
        }else{
            throw new IllegalArgumentException("Not a valid heuristic");
        }
    }

    
    /**
     * Compare two states by the cost. Let c1 and c2 be the costs of this state and the argument state s.
     * 
     * @return -1 if c1 < c2 
     *          0 if c1 = c2 
     *          1 if c1 > c2 
     *          
     * Call the method cost(). This comparison will be used in maintaining the OPEN list by the A* algorithm.
     */
    @Override
    public int compareTo(State s) throws IllegalStateException
    {
    	// TODO 
        if(this.cost() < s.cost()){
            return -1;
        }else if(this.cost() == s.cost()){
            return 0;
        }else if(this.cost() > s.cost()){
            return 1;
        } else{
            throw new IllegalStateException("State s is incorrect");
        }
    }
    

    /**
     * Return the value of the private variable numMismatchedTiles if it is non-negative, and compute its 
     * value otherwise. 
     * 
     * @return the number of mismatched tiles between this state and the goal state. 
     */
	private int computeNumMismatchedTiles()
	{
		// TODO 
        int x = 0;
        if(numMismatchedTiles > -1){
            return numMismatchedTiles;
        } else{
            int[][] goal = {{1,2,3},{8,0,4},{7,6,5}};
            for(int i = 0; i < 3; i++){
                for(int j = 0; j < 3; j++){
                    if(board[i][j] != 0 && board[i][j] != goal[i][j]){
                       x++;
                    }
                }
            }
            numMismatchedTiles = x;
        }
		return x; 
	}

	
	/**
	 * Return the value of the private variable ManhattanDistance if it is non-negative, and compute its value 
	 * otherwise.
	 * 
	 * @return the Manhattan distance between this state and the goal state. 
	 */
	private int computeManhattanDistance()
	{
		// TODO 
        int x = 0;
        if(ManhattanDistance > -1){
            return ManhattanDistance;
        }else{
            int[][] goalPos = {{0,0},{0,1},{0,2},{1,2},{2,2},{2,1},{2,0},{1,0},{1,1}};
            for(int i = 0; i < 3; i++){
                for(int j = 0; j < 3; j++){
                    if(board[i][j] != 0){
                        x += Math.abs(i-goalPos[board[i][j]][0]) + Math.abs(j - goalPos[board[i][j]][1]);
                    }
        }
	
	}
}
    ManhattanDistance = x;
	return x; 
    }
	
	
	/**
	 * Return the value of the private variable numSingleDoubleMoves if it is non-negative, and compute its value 
	 * otherwise. 
	 * 
	 * @return the value of the private variable numSingleDoubleMoves that bounds from below the number of moves, 
	 *         single or double, which will take this state to the goal state.
	 */
private int computeNumSingleDoubleMoves() {
    if (numSingleDoubleMoves > -1){
        return numSingleDoubleMoves;
    }
    int manhattan = computeManhattanDistance();
    int mismatched = computeNumMismatchedTiles();
    int adjacentPairs = 0;

    int[][] goal = {{1,2,3},{8,0,4},{7,6,5}};

    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            int a = board[i][j];
            if (a == 0) continue;

            if (j < 2) {
                int b = board[i][j + 1];
                if (b != 0) {
                 
                    for (int x = 0; x < 3; x++) {
                        for (int y = 0; y < 2; y++) {
                            if (goal[x][y] == a && goal[x][y + 1] == b)
                                adjacentPairs++;
                        }
                    }
                }
            }

            if (i < 2) {
                int b = board[i + 1][j];
                if (b != 0) {
                    for (int x = 0; x < 2; x++) {
                        for (int y = 0; y < 3; y++) {
                            if (goal[x][y] == a && goal[x + 1][y] == b)
                                adjacentPairs++;
                        }
                    }
                }
            }
        }
    }

    numSingleDoubleMoves = Math.max((int) Math.ceil(Math.max(0, manhattan - adjacentPairs) / 2.0),(int) Math.ceil(mismatched / 2.0));

    return numSingleDoubleMoves;
}



}

